server:
  port: 8002

spring:
  application:
    name: cloud-payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.60.142:3306/myself?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: root
    password: 123456

eureka:
  client:
    # 表示是否将自己注册进EureakaServer默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息  默认为true  单节点无所谓  集群必须设置true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 单机
      defaultZone: http://eureka7001.com:7001/eureka
      # 集群
      # defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8002
    prefer-ip-address: true
    # Eureka客户端向服务端发送心跳的时间间隔   单位秒
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2


mybatis:
  type-aliases-package: com.xinshiyun.springcloud.entities
  mapper-locations: classpath:mapper/*.xml
