server:
  port: 8004

spring:
  application:
    name: cloud-provider-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.60.142:3306/myself?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: root
    password: 123456

  cloud:
    zookeeper:
      connect-string: 192.168.60.231:2182

mybatis:
  type-aliases-package: com.xinshiyun.springcloud.entities
  mapper-locations: classpath:mapper/*.xml
